AppAuth.Web/Models/ErrorViewModel.cs
namespace AppAuth.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AppAuth.Web/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AppAuth.Web.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [MinLength(5)]
        public string Username { get; set; } = string.Empty;

        [Required]
        [MinLength(4)]
        public string Password { get; set; } = string.Empty;
    }
}

AppAuth.Web/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AppAuth.Web.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [MinLength(5)]
        public string Username { get; set; } = string.Empty;

        [Required]
        [MinLength(4)]
        public string Password { get; set; } = string.Empty;

        [Required]
        [Compare(nameof(Password))]
        public string ValidatePassword { get; set; } = string.Empty;
    }
}

AppAuth.Web/ViewModels/WeatherForecastViewModel.cs
namespace AppAuth.Web.ViewModels
{
    public class WeatherForecastViewModel
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF { get; set; }

        public string? Summary { get; set; }
    }
}

AppAuth.Web/Controllers/AuthController.cs
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using AppAuth.Web.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace AppAuth.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AuthController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Login(string ReturnUrl = "")
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View(new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel viewModel, string? ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            if (!ModelState.IsValid)
            {
                viewModel.Password = string.Empty;
                return View(viewModel);
            }

            if(string.IsNullOrEmpty(ReturnUrl))
            {
                ReturnUrl = Url.Content("~/");
            }

            // login a la API 
            string json = JsonSerializer.Serialize(viewModel);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var httpClient = _httpClientFactory.CreateClient("default");
            var response = await httpClient.PostAsync("auth/login", content);
            // token de sesion de la api
            string token = await response.Content.ReadAsStringAsync(); 

            // generar cookie para el navegador guardando el token
            var claims = new List<Claim>
            { 
                new Claim(ClaimTypes.Name, viewModel.Username),
                new Claim("jwt_key", token),
                new Claim(ClaimTypes.Role, "admin")
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(15),
                IsPersistent = true,
                IssuedUtc = DateTimeOffset.UtcNow
            };            

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            return LocalRedirect(ReturnUrl);
        }

        public IActionResult Register()
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                viewModel.Password = string.Empty;
                viewModel.ValidatePassword = string.Empty;
                return View(viewModel);
            }

            return View();
        }
    }
}

AppAuth.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppAuth.Web.Models;
using Microsoft.AspNetCore.Authorization;
using AppAuth.Web.ViewModels;

namespace AppAuth.Web.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public HomeController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IActionResult> Index()
    {
        var httpClient = _httpClientFactory.CreateClient("default");
        var response = await httpClient.GetFromJsonAsync<IEnumerable<WeatherForecastViewModel>>("WeatherForecast");        
        return View(response);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppAuth.Web/Views/Home/Index.cshtml
@model IEnumerable<AppAuth.Web.ViewModels.WeatherForecastViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<h1>Datos desde la api</h1>
<table class="table">
    <tr>
        <th>Fecha</th>
        <th>Temperature F</th>
        <th>Temperature C</th>
        <th>Summary</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Date</td>
            <td>@item.TemperatureF</td>
            <td>@item.TemperatureC</td>
            <td>@item.Summary</td>
        </tr>        
    }
</table>

AppAuth.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppAuth.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppAuth.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppAuth.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Iniciar Sesion</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Registrarse</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>